# coding: utf-8

"""
    Harmony Connect

    An easy to use API that helps you access the Factom blockchain.  # noqa: E501

    OpenAPI spec version: 1.0.17
    Contact: harmony-support@factom.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import harmony_connect_client
from harmony_connect_client.models.entry_search_response import EntrySearchResponse  # noqa: E501
from harmony_connect_client.rest import ApiException


class TestEntrySearchResponse(unittest.TestCase):
    """EntrySearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntrySearchResponse(self):
        """Test EntrySearchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harmony_connect_client.models.entry_search_response.EntrySearchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
