# coding: utf-8

"""
    Harmony Connect

    An easy to use API that helps you access the Factom blockchain.  # noqa: E501

    OpenAPI spec version: 1.0.17
    Contact: harmony-support@factom.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import harmony_connect_client
from harmony_connect_client.api.info_api import InfoApi  # noqa: E501
from harmony_connect_client.rest import ApiException


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = harmony_connect_client.api.info_api.InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_info(self):
        """Test case for get_all_info

        API Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
