# coding: utf-8

"""
    Harmony Connect

    An easy to use API that helps you access the Factom blockchain.  # noqa: E501

    OpenAPI spec version: 1.0.17
    Contact: harmony-support@factom.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ChainShort(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'chain_id': 'str',
        'entry_hash': 'str',
        'stage': 'str'
    }

    attribute_map = {
        'chain_id': 'chain_id',
        'entry_hash': 'entry_hash',
        'stage': 'stage'
    }

    def __init__(self, chain_id=None, entry_hash=None, stage=None):  # noqa: E501
        """ChainShort - a model defined in OpenAPI"""  # noqa: E501

        self._chain_id = None
        self._entry_hash = None
        self._stage = None
        self.discriminator = None

        self.chain_id = chain_id
        self.entry_hash = entry_hash
        self.stage = stage

    @property
    def chain_id(self):
        """Gets the chain_id of this ChainShort.  # noqa: E501

        This is the unique identifier created for each chain.  # noqa: E501

        :return: The chain_id of this ChainShort.  # noqa: E501
        :rtype: str
        """
        return self._chain_id

    @chain_id.setter
    def chain_id(self, chain_id):
        """Sets the chain_id of this ChainShort.

        This is the unique identifier created for each chain.  # noqa: E501

        :param chain_id: The chain_id of this ChainShort.  # noqa: E501
        :type: str
        """
        if chain_id is None:
            raise ValueError("Invalid value for `chain_id`, must not be `None`")  # noqa: E501

        self._chain_id = chain_id

    @property
    def entry_hash(self):
        """Gets the entry_hash of this ChainShort.  # noqa: E501

        The SHA256 Hash of the chain's first entry.  # noqa: E501

        :return: The entry_hash of this ChainShort.  # noqa: E501
        :rtype: str
        """
        return self._entry_hash

    @entry_hash.setter
    def entry_hash(self, entry_hash):
        """Sets the entry_hash of this ChainShort.

        The SHA256 Hash of the chain's first entry.  # noqa: E501

        :param entry_hash: The entry_hash of this ChainShort.  # noqa: E501
        :type: str
        """
        if entry_hash is None:
            raise ValueError("Invalid value for `entry_hash`, must not be `None`")  # noqa: E501

        self._entry_hash = entry_hash

    @property
    def stage(self):
        """Gets the stage of this ChainShort.  # noqa: E501

        The immutability stage that this chain has reached.  # noqa: E501

        :return: The stage of this ChainShort.  # noqa: E501
        :rtype: str
        """
        return self._stage

    @stage.setter
    def stage(self, stage):
        """Sets the stage of this ChainShort.

        The immutability stage that this chain has reached.  # noqa: E501

        :param stage: The stage of this ChainShort.  # noqa: E501
        :type: str
        """
        if stage is None:
            raise ValueError("Invalid value for `stage`, must not be `None`")  # noqa: E501

        self._stage = stage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChainShort):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
