# coding: utf-8

"""
    Harmony Connect

    An easy to use API that helps you access the Factom blockchain.  # noqa: E501

    OpenAPI spec version: 1.0.17
    Contact: harmony-support@factom.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class EntryListChain(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'chain_id': 'str',
        'href': 'str'
    }

    attribute_map = {
        'chain_id': 'chain_id',
        'href': 'href'
    }

    def __init__(self, chain_id=None, href=None):  # noqa: E501
        """EntryListChain - a model defined in OpenAPI"""  # noqa: E501

        self._chain_id = None
        self._href = None
        self.discriminator = None

        if chain_id is not None:
            self.chain_id = chain_id
        if href is not None:
            self.href = href

    @property
    def chain_id(self):
        """Gets the chain_id of this EntryListChain.  # noqa: E501

        The ID for this chain on the Factom blockchain.  # noqa: E501

        :return: The chain_id of this EntryListChain.  # noqa: E501
        :rtype: str
        """
        return self._chain_id

    @chain_id.setter
    def chain_id(self, chain_id):
        """Sets the chain_id of this EntryListChain.

        The ID for this chain on the Factom blockchain.  # noqa: E501

        :param chain_id: The chain_id of this EntryListChain.  # noqa: E501
        :type: str
        """

        self._chain_id = chain_id

    @property
    def href(self):
        """Gets the href of this EntryListChain.  # noqa: E501

        An API link to retrieve all information about this chain.  # noqa: E501

        :return: The href of this EntryListChain.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this EntryListChain.

        An API link to retrieve all information about this chain.  # noqa: E501

        :param href: The href of this EntryListChain.  # noqa: E501
        :type: str
        """

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EntryListChain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
